/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    applications: Application;
    levels: Level;
    faq: Faq;
    testimonials: Testimonial;
    'legal-pages': LegalPage;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    levels: LevelsSelect<false> | LevelsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    landing: Landing;
    'apply-form': ApplyForm;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    landing: LandingSelect<false> | LandingSelect<true>;
    'apply-form': ApplyFormSelect<false> | ApplyFormSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      notifyTeacher: TaskNotifyTeacher;
      deliverWebhook: TaskDeliverWebhook;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Заявка создаётся после первого шага формы. «Только шаг 1» — родитель оставил контакт, но не дошёл до цели и расписания.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  status: 'new' | 'in_review' | 'contacted' | 'waitlist' | 'enrolled' | 'declined';
  stage: 'step1' | 'complete';
  /**
   * Родитель отметил, что подходящего времени нет.
   */
  waitlist?: boolean | null;
  /**
   * Видны только сотрудникам.
   */
  adminNotes?: string | null;
  parentName: string;
  grade: number;
  contact: string;
  contactType?: ('phone' | 'telegram') | null;
  email: string;
  /**
   * Предположение родителя с карточки уровня. Окончательно уровень определяет преподаватель.
   */
  levelHint?: string | null;
  childName?: string | null;
  goal?: ('start' | 'understand' | 'olympiad' | 'confidence' | 'other') | null;
  goalOther?: string | null;
  desiredResult?: string | null;
  difficulties?: string | null;
  schedule?: ('weekday_afternoon' | 'weekday_evening' | 'weekend' | 'flexible')[] | null;
  scheduleComment?: string | null;
  timezone?:
    | (
        | 'Europe/Kaliningrad'
        | 'Europe/Moscow'
        | 'Europe/Samara'
        | 'Asia/Yekaterinburg'
        | 'Asia/Omsk'
        | 'Asia/Novosibirsk'
        | 'Asia/Irkutsk'
        | 'Asia/Yakutsk'
        | 'Asia/Vladivostok'
        | 'Asia/Magadan'
        | 'Asia/Kamchatka'
        | 'other'
      )
    | null;
  personalRoute?: ('yes' | 'maybe' | 'no') | null;
  consentPersonalData?: {
    accepted?: boolean | null;
    version?: string | null;
    acceptedAt?: string | null;
  };
  consentMarketing?: {
    accepted?: boolean | null;
    version?: string | null;
    acceptedAt?: string | null;
  };
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    term?: string | null;
    content?: string | null;
  };
  referrer?: string | null;
  landingPage?: string | null;
  device?: ('mobile' | 'tablet' | 'desktop') | null;
  step1At?: string | null;
  completedAt?: string | null;
  teacherNotifiedAt?: string | null;
  webhookDeliveredAt?: string | null;
  lastDeliveryError?: string | null;
  resumeTokenHash?: string | null;
  idempotencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Карточки уровней на главной. Цена, длительность и статус набора меняются здесь — без правки кода.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "levels".
 */
export interface Level {
  id: number;
  title: string;
  /**
   * Латиницей: start, school, olympiad. Уходит в заявку и аналитику — лучше не менять.
   */
  slug: string;
  /**
   * Например: «Основной маршрут»
   */
  badge?: string | null;
  /**
   * Например: 6–8 класс
   */
  grades: string;
  forWhom: string;
  whatHappens: string;
  outcome: string;
  lessonsCount: number;
  lessonMinutes: number;
  /**
   * «8 недель», «3 месяца»
   */
  durationLabel: string;
  price: number;
  /**
   * Пусто — не показывается
   */
  installmentNote?: string | null;
  /**
   * Например: +10 000 ₽ за модуль. Пусто — уровень не показывается в блоке.
   */
  personalRouteSurcharge?: string | null;
  enrollmentStatus: 'open' | 'few_left' | 'waitlist' | 'closed';
  /**
   * Например: старт 14 октября
   */
  nextStart?: string | null;
  /**
   * При статусе «Набор закрыт» и «Лист ожидания» кнопка сама меняется на «Встать в лист ожидания».
   */
  ctaLabel?: string | null;
  highlighted?: boolean | null;
  sortOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  sortOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Отзывы и результаты публикуются только с согласия семьи.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Например: «Мама ученика 7 класса»
   */
  author: string;
  text: string;
  consentConfirmed?: boolean | null;
  published?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Тексты размещаются только после согласования с владельцем проекта и юристом. Разработчик их не придумывает.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  slug: 'privacy' | 'consent' | 'offer';
  title: string;
  /**
   * Например: 1.0 от 01.11.2026
   */
  version: string;
  effectiveDate?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Пока отмечено, на странице виден баннер «Документ на согласовании».
   */
  isDraft?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Редактор не видит заявки и контакты родителей.
   */
  role: 'admin' | 'teacher' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'notifyTeacher' | 'deliverWebhook';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'notifyTeacher' | 'deliverWebhook') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'levels';
        value: number | Level;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  status?: T;
  stage?: T;
  waitlist?: T;
  adminNotes?: T;
  parentName?: T;
  grade?: T;
  contact?: T;
  contactType?: T;
  email?: T;
  levelHint?: T;
  childName?: T;
  goal?: T;
  goalOther?: T;
  desiredResult?: T;
  difficulties?: T;
  schedule?: T;
  scheduleComment?: T;
  timezone?: T;
  personalRoute?: T;
  consentPersonalData?:
    | T
    | {
        accepted?: T;
        version?: T;
        acceptedAt?: T;
      };
  consentMarketing?:
    | T
    | {
        accepted?: T;
        version?: T;
        acceptedAt?: T;
      };
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        term?: T;
        content?: T;
      };
  referrer?: T;
  landingPage?: T;
  device?: T;
  step1At?: T;
  completedAt?: T;
  teacherNotifiedAt?: T;
  webhookDeliveredAt?: T;
  lastDeliveryError?: T;
  resumeTokenHash?: T;
  idempotencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "levels_select".
 */
export interface LevelsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  badge?: T;
  grades?: T;
  forWhom?: T;
  whatHappens?: T;
  outcome?: T;
  lessonsCount?: T;
  lessonMinutes?: T;
  durationLabel?: T;
  price?: T;
  installmentNote?: T;
  personalRouteSurcharge?: T;
  enrollmentStatus?: T;
  nextStart?: T;
  ctaLabel?: T;
  highlighted?: T;
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author?: T;
  text?: T;
  consentConfirmed?: T;
  published?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  version?: T;
  effectiveDate?: T;
  content?: T;
  isDraft?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Тексты блоков главной. Уровни, цены, FAQ и отзывы — в отдельных разделах.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing".
 */
export interface Landing {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    subtitle: string;
    primaryCta: string;
    /**
     * Видна, только если тест включён в настройках
     */
    secondaryCta?: string | null;
    facts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    visual?: {
      eyebrow?: string | null;
      title?: string | null;
      text?: string | null;
    };
  };
  problems: {
    eyebrow?: string | null;
    title: string;
    intro?: string | null;
    items?:
      | {
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  method: {
    eyebrow?: string | null;
    title: string;
    intro?: string | null;
    steps?:
      | {
          title: string;
          text?: string | null;
          /**
           * Формулы оборачивайте в обратные кавычки: `2n + 1` — они будут набраны математическим шрифтом.
           */
          example?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  levels: {
    eyebrow?: string | null;
    title: string;
    intro?: string | null;
    notes?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  format: {
    eyebrow?: string | null;
    title: string;
    intro?: string | null;
    facts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    steps?:
      | {
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  teacher: {
    eyebrow?: string | null;
    name: string;
    role?: string | null;
    photo?: (number | null) | Media;
    bio?: string | null;
    facts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    quote?: string | null;
  };
  personalRoute: {
    eyebrow?: string | null;
    title: string;
    intro?: string | null;
    included?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    added?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    limitNote?: string | null;
  };
  community: {
    eyebrow?: string | null;
    title: string;
    intro?: string | null;
    points?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    cta: string;
  };
  howToJoin: {
    eyebrow?: string | null;
    title: string;
    intro?: string | null;
    steps?:
      | {
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  trust: {
    eyebrow?: string | null;
    title: string;
    intro?: string | null;
    facts?:
      | {
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  faq: {
    eyebrow?: string | null;
    title: string;
    intro?: string | null;
  };
  finalCta: {
    title: string;
    text?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apply-form".
 */
export interface ApplyForm {
  id: number;
  step1: {
    heading: string;
    lead?: string | null;
    promise?: string | null;
    submitLabel: string;
  };
  step2: {
    heading: string;
    lead?: string | null;
    submitLabel: string;
  };
  nextSteps?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  success: {
    heading: string;
    subheading?: string | null;
    nextText?: string | null;
    waitlistText?: string | null;
    contactPrompt?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  courseName: string;
  /**
   * Только реальный срок, который преподаватель соблюдает. Показывается на экране успеха.
   */
  responseTime: string;
  /**
   * Например: ИП Иванова И. И., ИНН 000000000000. Пусто — не показывается.
   */
  operatorDetails?: string | null;
  /**
   * https://t.me/username
   */
  telegramUrl?: string | null;
  telegramLabel?: string | null;
  email?: string | null;
  phone?: string | null;
  seoTitle: string;
  seoDescription: string;
  ogImage?: (number | null) | Media;
  /**
   * Только цифры. Пусто — аналитика выключена.
   */
  yandexMetrikaId?: string | null;
  /**
   * Решение — за юристом. Пока включено, показывается баннер cookie.
   */
  requireCookieConsent?: boolean | null;
  /**
   * Включать после запуска тестирования (этап 2).
   */
  showTestCta?: boolean | null;
  /**
   * Включать после запуска формы комьюнити (этап 5) — иначе кнопка ведёт на несуществующую страницу.
   */
  showTeachersBlock?: boolean | null;
  /**
   * Сохраняется в каждой заявке. Меняйте вместе с текстом документа /consent.
   */
  consentVersion: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing_select".
 */
export interface LandingSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        primaryCta?: T;
        secondaryCta?: T;
        facts?:
          | T
          | {
              text?: T;
              id?: T;
            };
        visual?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
            };
      };
  problems?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  method?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        steps?:
          | T
          | {
              title?: T;
              text?: T;
              example?: T;
              id?: T;
            };
      };
  levels?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        notes?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  format?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        facts?:
          | T
          | {
              text?: T;
              id?: T;
            };
        steps?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  teacher?:
    | T
    | {
        eyebrow?: T;
        name?: T;
        role?: T;
        photo?: T;
        bio?: T;
        facts?:
          | T
          | {
              text?: T;
              id?: T;
            };
        quote?: T;
      };
  personalRoute?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        included?:
          | T
          | {
              text?: T;
              id?: T;
            };
        added?:
          | T
          | {
              text?: T;
              id?: T;
            };
        limitNote?: T;
      };
  community?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
        cta?: T;
      };
  howToJoin?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        steps?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  trust?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        facts?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  finalCta?:
    | T
    | {
        title?: T;
        text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apply-form_select".
 */
export interface ApplyFormSelect<T extends boolean = true> {
  step1?:
    | T
    | {
        heading?: T;
        lead?: T;
        promise?: T;
        submitLabel?: T;
      };
  step2?:
    | T
    | {
        heading?: T;
        lead?: T;
        submitLabel?: T;
      };
  nextSteps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  success?:
    | T
    | {
        heading?: T;
        subheading?: T;
        nextText?: T;
        waitlistText?: T;
        contactPrompt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  courseName?: T;
  responseTime?: T;
  operatorDetails?: T;
  telegramUrl?: T;
  telegramLabel?: T;
  email?: T;
  phone?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  yandexMetrikaId?: T;
  requireCookieConsent?: T;
  showTestCta?: T;
  showTeachersBlock?: T;
  consentVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskNotifyTeacher".
 */
export interface TaskNotifyTeacher {
  input: {
    applicationId: string;
    event: string;
  };
  output: {
    skipped?: boolean | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDeliverWebhook".
 */
export interface TaskDeliverWebhook {
  input: {
    applicationId: string;
    event: string;
  };
  output: {
    skipped?: boolean | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}